[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.environment]
  NODE_VERSION = "18"
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"
  CI = "true"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"


[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true