version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Gatsby site
          command: npm run build
      - run:
          name: Deploy to Netlify
          command: npx netlify-cli deploy --prod --dir=public

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
