version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Gatsby site
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Deploy to Netlify
          command: npx netlify-cli deploy --prod --dir=public --auth $NETLIFY_ACCESS_TOKEN --site $NETLIFY_SITE_ID

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
