name: Trigger Test (No Build/Deploy)

concurrency: 
  group: "netlify-deploy"
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [webhook]

jobs:
  debug-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Information
        run: |
          echo "=== Event Details ==="
          echo "Event Name: ${{ github.event_name }}"
          echo "Trigger Time: ${{ github.event.timestamp }}"
          echo "Action Type: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: Debug Webhook Payload
        run: |
          echo "=== Webhook Payload ==="
          echo "Sender: ${{ github.event.sender.login }}"
          echo "Full Event: ${{ toJson(github.event) }}"
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"

      - name: Execution Timestamp
        run: |
          echo "Current Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
