name: Trigger Test (No Build/Deploy)

on:
  # StrapiからのWebhookトリガーを想定（repository_dispatchを使用）
  repository_dispatch:
    types: [webhook]

jobs:
  trigger-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Webhook Trigger
        run: |
          echo "✅ Webhook Trigger Received!"
          echo "Event Type: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"

      - name: Dummy Step for Logging
        run: |
          echo "Trigger Time: ${{ github.event.timestamp }}"
          echo "Sender: ${{ github.event.sender.login }}"
